name: simple-uam

channels:
  - default
  - conda-forge
  # - CadQuery

dependencies:
  - python=3.9 # Some packages don't support 3.10
  ## Environment and Package Management ##
  - pre-commit
  - pip
  - pip:
      - invoke
      - copier
      - markupsafe==2.0.1
      - setuptools>=62.0.0
      - pdm
  ## 3D Modeling and Cad ##
  # - cadquery::CadQuery=master
  # - cq-editor::CadQuery=master
  # - occt::CadQuery
  # - pythonocc-core

variables:
  # Removes the "Setuptools is replacing distutils." warning.
  SETUPTOOLS_USE_DISTUTILS: stdlib
