site_name: "Simple UAM Pipeline"
site_description: "A set of libraries and wrappers around the SWRi athens-uav project.  "
site_url: "https://LOGiCS-Project.github.io/swri-simple-uam-pipeline"
repo_url: "https://github.com/LOGiCS-Project/swri-simple-uam-pipeline"
repo_name: "LOGiCS-Project/swri-simple-uam-pipeline"
site_dir: "site"
watch: [README.md, CONTRIBUTING.md, simple_uam]

nav:
  - Home:
    - Overview: index.md
    - Installation: # setup/*
      - Introduction: setup/intro.md
      - Notes: setup/notes.md
      - Worker Deployment: # setup/worker/*
        - Choosing a Topology: setup/worker/topology.md # TODO
      - AWS (Network): setup/aws-network.md # TODO
      - AWS (Instance): setup/aws-instance.md # TODO
      - General Setup: setup/general.md # TODO
      - License Server: setup/license_server.md # TODO
      - Broker & Backend: setup/broker.md # TODO
      - Corpus Database: setup/graph.md # TODO
      - Static Corpus: setup/corpus.md # TODO
      - Worker Node: setup/worker.md # TODO
      - Client Node: setup/client.md # TODO
    - Usage: # TODO
      - Configuration: usage/config.md # TODO
      - Craidl: usage/craidl.md # TODO
      - License Server: usage/license.md # TODO
      - Workspaces: usage/workspaces.md # TODO
      - Workers: usage/workers.md # TODO
      - Clients: usage/clients.md # TODO
    - License: license.md # TODO
  # defer to gen-files + literate-nav # TODO
  - Code Reference: reference/ # TODO
  - Contributing: contributing.md # TODO

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - content.tabs.link
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: light blue
    accent: light blue
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue
    accent: yellow
    toggle:
      icon: material/weather-night
      name: Switch to light mode

extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
- admonition
- callouts
- attr_list
- md_in_html
- pymdownx.emoji
- pymdownx.details
- pymdownx.magiclink
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- toc:
    permalink: true
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true


plugins:
- search
- markdown-exec
- gen-files:
    scripts:
    - docs/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings
