site_name: "Simple UAM Pipeline"
site_description: "A set of libraries and wrappers around the SWRi athens-uav project.  "
site_url: "https://LOGiCS-Project.github.io/swri-simple-uam-pipeline"
repo_url: "https://github.com/LOGiCS-Project/swri-simple-uam-pipeline"
repo_name: "LOGiCS-Project/swri-simple-uam-pipeline"
site_dir: "site"
watch: [README.md, CONTRIBUTING.md]

nav:
  - Home:
    - Overview: index.md
    - Install:
      - Introduction: setup/intro.md
      - AWS (Network): setup/aws-network.md
      - AWS (Instance): setup/aws-instance.md
      - General Setup: setup/general.md
      - License Server: setup/license_server.md
      - Broker & Backend: setup/broker.md
      - Corpus Database: setup/graph.md
      - Static Corpus: setup/corpus.md
      - Worker Node: setup/worker.md
      - Client Node: setup/client.md
    - Usage:
      - Configuration: usage/config.md
      - Craidl: usage/craidl.md
      - License Server: usage/license.md
      - Workspaces: usage/workspaces.md
      - Workers: usage/workers.md
      - Clients: usage/clients.md
    - License: license.md
  # defer to gen-files + literate-nav
  - Code Reference: reference/
  - Contributing: contributing.md

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - content.tabs.link
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode

extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
- admonition
- callouts
- attr_list
- md_in_html
- pymdownx.emoji
- pymdownx.details
- pymdownx.magiclink
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- toc:
    permalink: true
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true


plugins:
- search
- markdown-exec
- gen-files:
    scripts:
    - docs/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings
